@startuml
!theme blueprint

interface IAnimationClip {
  + () 
}

class dummyAnimationClip {

}
IAnimationClip <|-- dummyAnimationClip

interface IPlayer {
  + Play(clip IAnimationClip)
  + Stop()
}
IAnimationClip <-- IPlayer

class dummyPlayer
IPlayer <|-- dummyPlayer


class animationState {
}

class transition {
  + from animationState
  + to animationState
  + trigger Func

  + Check()
  + IsFrom()
}
transition --> animationState


class asm {
  + currentState animationState
  + transitions [transition]
  + states [animationState]
  + void AddTransition(transition)
  + void AddState(transition)
  + void Update(string, any)
  + asm New(IPlayer)
}
asm "1" o-> "1..n" animationState
asm "1" o-> "1..n" transition

class exampleApp
@enduml
